
kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: new-dep
spec:
  ports:
    - port: 80                              # Containers port exposed
      targetPort: 80  
      nodePort: 30008                   # Pods port
                     
                     # Apply this service to any pods which has the specific label
  type: Nodeport
  selector:
    name: deploy-img 