
kind: Service                             # Defines to create Service type Object
apiVersion: v1
metadata:
  name: new-deploy
spec:
  ports:
    - port: 6379                               # Containers port exposed
      targetPort: 80                     # Pods port
  selector:
    name: deploy-img                    # Apply this service to any pods which has the specific label
  type: ClusterIP